misc fixes to install, keyboard backlight, sound control, etc

diff --git a/bin/keyboard-backlight b/bin/keyboard-backlight
--- a/bin/keyboard-backlight
+++ b/bin/keyboard-backlight
@@ -1,69 +1,107 @@
 #!/bin/bash
-##############################################################################
-# keyboard-backlight
-# -----------
-# For when you are running leeenux on a Mac and it needs some help
-#
-# Usage:
-# 	keyboard-backlight {up,down,total,off}
-#
-# :authors: Jess Frazelle, @jessfraz
-# :date: 8 June 2015
-# :version: 0.0.1
-##############################################################################
-set -e
-set -o pipefail
 
-BACKLIGHT=$(cat /sys/class/leds/smc::kbd_backlight/brightness)
-INCREMENT=15
+## Keyboard backlight control for asus Zenbook
 
-if [ $UID -ne 0 ]; then
-	echo "Please run this program as superuser"
-	exit 1
-fi
-
-SET_VALUE=0
-case $1 in
-
-	up)
-		TOTAL=$((BACKLIGHT + INCREMENT))
-		if [ "$TOTAL" -gt "255" ]; then
-			exit 1
-		fi
-		SET_VALUE=1
-		;;
-	down)
-		TOTAL=$((BACKLIGHT - INCREMENT))
-		if [ "$TOTAL" -lt "0" ]; then
-			exit 1
-		fi
-		SET_VALUE=1
-		;;
-	total)
-		TEMP_VALUE=$BACKLIGHT
-		while [ "$TEMP_VALUE" -lt "255" ]; do
-			TEMP_VALUE=$((TEMP_VALUE + 1))
-			if [ $TEMP_VALUE -gt "255" ]; then
-				TEMP_VALUE=255
-			fi
-			echo $TEMP_VALUE > /sys/class/leds/smc::kbd_backlight/brightness
-		done
-		;;
-	off)
-		TEMP_VALUE=$BACKLIGHT
-		while [ "$TEMP_VALUE" -gt "0" ]; do
-			TEMP_VALUE=$((TEMP_VALUE - 1))
-			if [ $TEMP_VALUE -lt "0" ]; then
-				TEMP_VALUE=0
-			fi
-			echo $TEMP_VALUE > /sys/class/leds/smc::kbd_backlight/brightness
-		done
-		;;
-	*)
-		echo "Use: keyboard-backlight up|down|total|off"
-		;;
-esac
-
-if [ $SET_VALUE -eq "1" ]; then
-	echo "$TOTAL" > /sys/class/leds/smc::kbd_backlight/brightness
+# backlight_get
+#       Print current keyboard brightness from UPower to stdout.
+backlight_get()
+{
+    dbus-send --type=method_call --print-reply=literal --system         \
+        --dest='org.freedesktop.UPower'                                 \
+        '/org/freedesktop/UPower/KbdBacklight'                          \
+        'org.freedesktop.UPower.KbdBacklight.GetBrightness'             \
+        | awk '{print $2}'
+}
+ 
+# backlight_get_max
+#       Print the maximum keyboard brightness from UPower to stdout.
+backlight_get_max()
+{
+    dbus-send --type=method_call --print-reply=literal --system       \
+        --dest='org.freedesktop.UPower'                               \
+        '/org/freedesktop/UPower/KbdBacklight'                        \
+        'org.freedesktop.UPower.KbdBacklight.GetMaxBrightness'        \
+        | awk '{print $2}'
+}
+ 
+# backlight_set NUMBER
+#       Set the current backlight brighness to NUMBER, through UPower
+backlight_set()
+{
+    value="$1"
+    if test -z "${value}" ; then
+        echo "Invalid backlight value ${value}"
+    fi
+ 
+    dbus-send --type=method_call --print-reply=literal --system       \
+        --dest='org.freedesktop.UPower'                               \
+        '/org/freedesktop/UPower/KbdBacklight'                        \
+        'org.freedesktop.UPower.KbdBacklight.SetBrightness'           \
+        "int32:${value}}"
+}
+ 
+# backlight_change [ UP | DOWN | NUMBER ]
+#       Change the current backlight value upwards or downwards, or
+#       set it to a specific numeric value.
+backlight_change()
+{
+    change="$1"
+    if test -z "${change}" ; then
+        echo "Invalid backlight change ${change}."                    \
+            "Should be 'up' or 'down'." >&2
+        return 1
+    fi
+ 
+    case ${change} in
+    [1234567890]|[[1234567890][[1234567890])
+        current=$( backlight_get )
+        max=$( backlight_get_max )
+        value=$( expr ${change} + 0 )
+        if test ${value} -lt 0 || test ${value} -gt ${max} ; then
+            echo "Invalid backlight value ${value}."                  \
+                "Should be a number between 0 .. ${max}" >&2
+            return 1
+        else
+            backlight_set "${value}"
+            notify-send -t 800 "Keyboard brightness set to ${value}"
+        fi
+        ;;
+ 
+    [uU][pP])
+        current=$( backlight_get )
+        max=$( backlight_get_max )
+        if test "${current}" -lt "${max}" ; then
+            value=$(( ${current} + 1 ))
+            backlight_set "${value}"
+            notify-send -t 800 "Keyboard brightness set to ${value}"
+        fi
+        ;;
+ 
+    [dD][oO][wW][nN])
+        current=$( backlight_get )
+        if test "${current}" -gt 0 ; then
+            value=$(( ${current}  - 1 ))
+            backlight_set "${value}"
+            notify-send -t 800 "Keyboard brightness set to ${value}"
+        fi
+        ;;
+ 
+    *)
+        echo "Invalid backlight change ${change}." >&2
+        echo "Should be 'up' or 'down' or a number between"           \
+            "1 .. $( backlight_get_max )" >&2
+        return 1
+        ;;
+    esac
+}
+ 
+if test $# -eq 0 ; then
+    current_brightness=$( backlight_get )
+    notify-send -t 800 "Keyboard brightness is ${current_brightness}"
+else
+    # Handle multiple backlight changes, e.g.:
+    #   backlight.sh up up down down up
+    for change in "$@" ; do
+        backlight_change "${change}"
+    done
 fi
